export const FORTUNE_WHEEL_SETTINGS = 'FORTUNE_WHEEL_SETTINGS'
export const HANDLE_WHEEL_SPINNING_END = 'HANDLE_WHEEL_SPINNING_END'
export const HANDLE_WHEEL_SPINNING_START = 'HANDLE_WHEEL_SPINNING_START'
export const HANDLE_CURRENT_SELECTED_VALUE = 'HANDLE_CURRENT_SELECTED_VALUE'
